### ISSUE TITLE
Simple CSV test fails

### ISSUE THREAD

**Issue by pheyvaer** [thesmartenergy/sparql-generate#13]
Hi,

When trying the test [simplecsv](https://github.com/thesmartenergy/sparql-generate/tree/master/sparql-generate-jena/src/test/resources/simplecsv), I get only the triples of the second row. The triples of the first row are not generated (or outputted). I compared it with the expected output. Could you have a look at this problem?

**Comment by maximelefrancois86** [comment]
Hi, thanks for spotting this, it is fixed now.
