### ISSUE TITLE
 How to generate rdf:list with sparql-generate ?

### ISSUE THREAD

**Issue by ltemal94** [thesmartenergy/sparql-generate#3]
Hi,
I am using spargl to generate rdf triples from a json file.
For my needs, I would like to generate  rdf:List from a set of json values.

My json file is like 

{
    "att": [
              { "att1": "v1_1",
                "att2": "v2_1"
                },
                { "att1": "v1_2",
                 "att2":  "v2_2"
                },
                { "att1": "v1_3",
                 "att2":  "v2_3"
                }
]}

I would like to generate rdf like the following
`<myURI> ex:hasList ([ex:value "V1_1"^^xsd:int] [ex:value "V1_2"^^xsd:int] [ex:value "V1_3"^^xsd:int]); 
                ex:hasList ([ex:value "V2_1"^^xsd:dateTime] [ex:value "V2_2"^^xsd:dateTime] [ex:value  "V2_3"^^xsd:dateTime]).`

Could you, please, give an example of a spargl query that allow to generate the corresponding triples with the right code.

Thanks for your help.

**Comment by maximelefrancois86** [comment]
Dear Lynda,

This is an identified limitation of SPARQL-Generate for now.
More generally, it is a difficult task to construct lists from solution
mappings with SPARQL 1.1.
Also to the best of our knowledge, other mapping-based RDF Generation
languages also lack this capability.

We have ideas and actual plans for doing this generically in the near
future, but they are not implemented yet.
In the meantime, Mohammad Noorani Bakerally is proposing a workaround for
JSON in the form of a new SPARQL-Generate iterator, that from your JSON
document outputs the following list of literals:

"""{ "element": {"att1": "v1_1", "att2": "v2_1"}, "position": 1, "hasNext"
: true }"""^^<urn:iana:mime:application:json>
"""{ "element": {"att1": "v1_2", "att2": "v2_2"}, "position": 2, "hasNext"
: true }"""^^<urn:iana:mime:application:json>
"""{ "element": {"att1": "v1_3", "att2": "v2_3"}, "position": 3, "hasNext"
: false }"""^^<urn:iana:mime:application:json>

Then the writing of a SPARQL-Generate query that does what you need is
straightforward. The answer to your example will be available as a new unit
test named generatelistjson, which will be part of the new release planned
for this evening.

Kind regards,
Maxime Lefrançois

**Comment by noorbakerally** [comment]
Dear Lynda,

[this](https://github.com/thesmartenergy/sparql-generate-jena/blob/master/src/test/resources/generatelistjson/query.rqg) could be a potential temporary query for what you want to achieve. As you can see, in place of blank nodes, we have used IRIs as currently, even with a CONSTRUCT SPARQL clause, it is not possible to generate a list from a purely RDF graph. We are working on an extension to address this
