### ISSUE TITLE
sparql-generate website missing

### ISSUE THREAD

**Issue by stain** [thesmartenergy/sparql-generate#5]
http://w3id.org/sparql-generate gives 404

.. as there is no `gh-pages` branch

**Comment by stain** [comment]
Should the w3id purl be redirected to http://ci.emse.fr/sparql-generate/ instead?

**Comment by maximelefrancois86** [comment]
yes indeed, the following two URIs are wrong:
 - http://thesmartenergy.github.io/sparql-generate-jena/
 - http://ci.emse.fr/sparql-generate

The only valid one (which is mentioned in the README and the .htaccess) is:
 - http://ci.emse.fr/sparql-generate/

Is there any other problem ?

Kind regards,
Maxime

**Comment by maximelefrancois86** [comment]
ok I see. 

This is related to pull request #350

we updated the website and its location 
deleted the github site yesterday, and created the new site today.

this is why it did not work this morning.

**Comment by stain** [comment]
Ah, I see you have already submitted perma-id/w3id.org#350 to fix the w3id links
