### ISSUE TITLE
Executable not working for a test case example

### ISSUE THREAD

**Issue by maximelefrancois86** [thesmartenergy/sparql-generate#7]
Steps to reproduce the error:
download the jar and save it into the top level of the github checkout 

call the executable from the command line with the following statement:

java -jar sparql-generate-jena.jar -qf sparql-generate-jena/src/test/resources/simplecsv/query.rqg -c http://example.com/airport.csv=sparql-generate-jena/src/test/resources/simplecsv/airport.csv -f TTL

Bug reported by Georg Ferdinand Schneider, M.Sc., 
Fraunhofer Institute for Building Physics IBP, Nuremberg Branch

**Comment by noorbakerally** [comment]
Hi.

branch develop updated with the bug solved for command line, check it then
merge with master

Noor

**Comment by GeorgFerdinandSchneider** [comment]
Hi Noor!

thanks for checking and updating. Did you also update the executable which may be downloaded from http://ci.emse.fr/sparql-generate/sparql-generate-jena.jar ?

Thanks and best,

Georg

**Comment by noorbakerally** [comment]
hi Georg,

no, not yet,

to get the jar:
- clone the repository
- enter the top-level directory i.e. sparql-generate
- type the command to package it with maven: mvn package
- then enter the directory sparql-generate/sparql-generate-jena/target
- the jar is sparql-generate-jena-1.2-SNAPSHOT.jar

regards,
Noor

**Comment by GeorgFerdinandSchneider** [comment]
Thanks for the hint!

after compiling everything works fine e.g.:

java -jar sparql-generate-jena-1.2-SNAPSHOT.jar -qf query.rqg -c http://example.com/airport.csv=airport.csv -f TTL
works

java -jar sparql-generate-jena-1.2-SNAPSHOT.jar -qf query.rqg -c http://example.com/transport.xml=transport.xml -f TTL
works

java -jar sparql-generate-jena-1.2-SNAPSHOT.jar -qf xmltest1/query.rqg -c http://example.com/transport.xml=xmltest1/transport.xml -f TTL
works

so far I would propose to mark the issue to fixed

**Comment by maximelefrancois86** [comment]
Great, thanks to Noor,
I hadn't time to put the latest jar online, but we have more plans for v1.2. 
at least we now know how to get a working version.
