### ISSUE TITLE
Server connectivity/ Connection reset

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [thesmartenergy/sparql-generate#8]
Hello everyone,

there may be an issue with webserver connectivity setting back the connection when performing a different query from the example query in the "Test it online feature".

Query and data as specified by @maximelefrancois86 for the simpleCSV test case applying it in the "Test it online" feature: 

BASE http://example.com/ 
PREFIX iter: http://w3id.org/sparql-generate/iter/
PREFIX fn: http://w3id.org/sparql-generate/fn/
PREFIX wgs84_pos: http://www.w3.org/2003/01/geo/wgs84_pos#
PREFIX transit: http://vocab.org/transit/terms/
PREFIX xsd: http://www.w3.org/2001/XMLSchema# 

GENERATE { 
  ?airportURI a transit:Stop;
        transit:route ?route1;
        wgs84_pos:lat ?lat;
        wgs84_pos:long ?long .

}
ITERATOR iter:CSV(?source) AS ?bus
WHERE {
    BIND( fn:CSV(?bus, "id" ) AS ?id )
    BIND( fn:CSV(?bus, "stop" ) AS ?route )
    BIND(STRDT(STR(?route), xsd:int) AS ?route1)
    BIND( fn:CSV(?bus, "longitude" ) AS ?long )
    BIND( fn:CSV(?bus, "latitude" ) AS ?lat )
    BIND (URI(CONCAT("http://airport.example.com/",?id)) AS ?airportURI)
}

variable: source

id,stop,latitude,longitude
6523,25,50.901389,4.484444
7000,40,56.901389,4.584444

---

Applying this on the website "Test it online" form the error reported is: "104 Connection reset by peer"

Full error message:

CacheHost: proxy.hoki.ibp.fraunhofer.de 
ErrPage: ERR_READ_ERROR 
Err: (104) Connection reset by peer 
TimeStamp: Fri, 02 Sep 2016 15:04:30 GMT 
ClientIP: 10.39.190.19 
ServerIP: 193.49.174.45 
HTTP Request: 
GET /sparql-generate/api/transform?source=text&queryuri=&query=BASE+%3Chttp%3A%2F%2Fexample.com%2F%3E+%0D%0APREFIX+iter%3A+%3Chttp%3A%2F%2Fw3id.org%2Fsparql-generate%2Fiter%2F%3E%0D%0APREFIX+fn%3A+%3Chttp%3A%2F%2Fw3id.org%2Fsparql-generate%2Ffn%2F%3E%0D%0APREFIX+wgs84_pos%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2003%2F01%2Fgeo%2Fwgs84_pos%23%3E%0D%0APREFIX+transit%3A+%3Chttp%3A%2F%2Fvocab.org%2Ftransit%2Fterms%2F%3E%0D%0APREFIX+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E+%0D%0A%0D%0AGENERATE+%7B+%0D%0A++%3FairportURI+a+transit%3AStop%3B%0D%0A++++++++transit%3Aroute+%3Froute1%3B%0D%0A++++++++wgs84_pos%3Alat+%3Flat%3B%0D%0A++++++++wgs84_pos%3Along+%3Flong+.%0D%0A%0D%0A%7D%0D%0AITERATOR+iter%3ACSV%28%3Fsource%29+AS+%3Fbus%0D%0AWHERE+%7B%0D%0A++++BIND%28+fn%3ACSV%28%3Fbus%2C+%22id%22+%29+AS+%3Fid+%29%0D%0A++++BIND%28+fn%3ACSV%28%3Fbus%2C+%22stop%22+%29+AS+%3Froute+%29%0D%0A++++BIND%28STRDT%28STR%28%3Froute%29%2C+xsd%3Aint%29+AS+%3Froute1%29%0D%0A++++BIND%28+fn%3ACSV%28%3Fbus%2C+%22longitude%22+%29+AS+%3Flong+%29%0D%0A++++BIND%28+fn%3ACSV%28%3Fbus%2C+%22latitude%22+%29+AS+%3Flat+%29%0D%0A++++BIND+%28URI%28CONCAT%28%22http%3A%2F%2Fairport.example.com%2F%22%2C%3Fid%29%29+AS+%3FairportURI%29%0D%0A%7D%0D%0A&var=source&message=id%2Cstop%2Clatitude%2Clongitude%0D%0A6523%2C25%2C50.901389%2C

**Comment by GeorgFerdinandSchneider** [comment]
I tested this problem on a Windows 7 and Ubuntu 14.04 system using Google Chrome and Mozilla Firefox Webbrowsers.

Also I used different internet connections (private and company)

**Comment by maximelefrancois86** [comment]
Hello Georg, is the problem still occurring ?

**Comment by GeorgFerdinandSchneider** [comment]
Hi Maxime,,

yes I think so. tested your new interface/layout and it works fine.

Solved
